CREATE SCHEMA CRC AUTHORIZATION DBO;
GO
CREATE SCHEMA HIVE AUTHORIZATION DBO;
GO
CREATE SCHEMA ONT AUTHORIZATION DBO;
GO
CREATE SCHEMA PM AUTHORIZATION DBO;
GO
CREATE SCHEMA WORK AUTHORIZATION DBO;
GO