INSERT INTO CRC.CONCEPT_DIMENSION
    (CONCEPT_PATH, CONCEPT_CD, NAME_CHAR, SOURCESYSTEM_CD)
  SELECT C_FULLNAME, C_BASECODE, C_NAME, SOURCESYSTEM_CD
  FROM ONT.I2B2
  WHERE C_SYNONYM_CD='N' AND C_FACTTABLECOLUMN='concept_cd' 
    AND C_TABLENAME='concept_dimension' AND C_COLUMNNAME='concept_path' 
    AND M_APPLIED_PATH='@' AND C_BASECODE<>''
