set zip="C:\Program Files\7-Zip\7z.exe"
call %zip% x ..\CQ2.zip -otmp\ -r

set DB_NAME=CQ2
sqlcmd -S . -d master -v YourProfilesServerName="." DatabaseName="%DB_NAME%" -E -i SQL_Scripts\CreateDatabase.sql 
sqlcmd -S . -d "%DB_NAME%" -E -i "SQL_Scripts\CreateSchema.sql"

REM TABLE AND VIEWS
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\CODE_LOOKUP.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\CONCEPT_DIMENSION.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\CQ2_CONCEPT_PATH.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\CQ2_CONCEPT_PATH_CODE.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\CQ2_FACT_COUNTS_CONCEPT.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\CQ2_FACT_COUNTS_CONCEPT_PATIENT.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\CQ2_FACT_COUNTS_PATH.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\CQ2_FACT_COUNTS_PATH_PATIENT.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\CQ2_PARAMS.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\CQ2_SKETCH_PATH15x256.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\CQ2_SKETCH_PATH8x256.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\CQ2_SKETCH_PATIENT.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\ENCOUNTER_MAPPING.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\MODIFIER_DIMENSION.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\OBSERVATION_FACT.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\OBSERVATION_FACT_ORIG.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\PATIENT_DIMENSION.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\PATIENT_DIMENSION_ORIG.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\PATIENT_MAPPING.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\PDO_OUTPUT_SET_METADATA.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\PROVIDER_DIMENSION.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\QT_ANALYSIS_PLUGIN.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\QT_ANALYSIS_PLUGIN_RESULT_TYPE.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\QT_BREAKDOWN_PATH.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\QT_QUERY_STATUS_TYPE.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\QT_QUERY_MASTER.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\QT_QUERY_INSTANCE.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\QT_QUERY_RESULT_TYPE.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\QT_QUERY_RESULT_INSTANCE.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\QT_PATIENT_ENC_COLLECTION.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\QT_PATIENT_SET_COLLECTION.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\QT_PDO_QUERY_MASTER.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\QT_PRIVILEGE.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\QT_QUERY_RESULT_SKETCH.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\QT_XML_RESULT.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\VISIT_DIMENSION.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\VISIT_DIMENSION_ORIG.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\AuthenticateLog.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\CRC_ANALYSIS_JOB.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\CRC_DB_LOOKUP.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\ErrorLog.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\IM_DB_LOOKUP.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\MessageLog.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\ONT_DB_LOOKUP.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\SERVICE_LOOKUP.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\WORK_DB_LOOKUP.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\ONT\I2B2.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\ONT\ONT_PROCESS_STATUS.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\ONT\SCHEMES.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\ONT\TABLE_ACCESS.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_APPROVALS.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_APPROVALS_PARAMS.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_CELL_DATA.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_CELL_PARAMS.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_GLOBAL_PARAMS.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_HIVE_DATA.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_HIVE_PARAMS.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_PROJECT_DATA.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_PROJECT_PARAMS.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_PROJECT_REQUEST.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_PROJECT_USER_PARAMS.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_PROJECT_USER_ROLES.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_ROLE_REQUIREMENT.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_USER_DATA.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_USER_LOGIN.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_USER_PARAMS.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\PM_USER_SESSION.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\WORK\WORKPLACE.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\WORK\WORKPLACE_ACCESS.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\vwCQ2_ConceptDimension.View.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\vwCQ2_Ontology.View.sql"


REM FUNCTIONS
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\fnDate2Str.UserDefinedFunction.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\fnHasUserRole.UserDefinedFunction.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\fnSketchEstimate.UserDefinedFunction.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\fnStr2Bit.UserDefinedFunction.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\fnStr2BitDefault.UserDefinedFunction.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\fnXMLValue.UserDefinedFunction.sql"


REM PROCEDURES
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\uspGetResponse.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\uspRunGetNameInfo.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\uspRunPDO.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\uspRunPSM.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\uspRunQueryInstance.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\uspRunQueryInstanceBreakdown.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\uspRunQueryInstanceQM.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\uspRunQueryInstanceSubquery.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\uspUpdateAllSteps.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\uspUpdateStep1CreateDataTables.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\uspUpdateStep2LoadDataTables.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\uspUpdateStep3IndexDataTables.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\uspUpdateStep4CreateCQ2Tables.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\uspUpdateStep5SwapTables.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\CRC\uspUpdateStep6DropOldTables.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\uspGetCellSchema.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\uspGetMessageHeader.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\uspGetNewID.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\uspGetResponse.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\uspGetResponse_PHP.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\uspGetResponseHeader.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\HIVE\uspGetStandardResponse.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\ONT\uspGetResponse.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\ONT\uspRunOperation.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\uspConvertToToken.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\uspGetAuthenticate.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\uspGetResponse.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\uspGetServices.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\PM\uspRegister.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\WORK\uspGetResponse.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\WORK\uspRunOperation.StoredProcedure.sql"


REM OPTIONAL OBJECTS
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\dbo\x.Table.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\dbo\uspGetSqlDropObjects.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\dbo\uspGetSqlFullSchema.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\dbo\uspGetSqlTableData.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\dbo\uspGetSqlTableDataAll.StoredProcedure.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "..\..\Database\Schema\dbo\uspGetSqlTableSchema.StoredProcedure.sql"

sqlcmd -S . -d "%DB_NAME%" -E -i "tmp\CQ2\Database\CreateFunctionsProcedures.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "tmp\CQ2\Database\CreateOptionalObjects.sql"

sqlcmd -S . -d "%DB_NAME%" -E -i "tmp\CQ2\Database\Demodata\DefaultData.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "tmp\CQ2\Database\Demodata\DemoOntologyPart1.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "tmp\CQ2\Database\Demodata\DemoOntologyPart2.sql"

sqlcmd -S . -d "%DB_NAME%" -E -i "SQL_Scripts\LoadConceptDimension.sql"

sqlcmd -S . -d %DB_NAME% -E -Q "EXEC CRC.uspUpdateStep1CreateDataTables"

sqlcmd -S . -d "%DB_NAME%" -E -i "tmp\CQ2\Database\Demodata\DemoDataPatientVisit.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "tmp\CQ2\Database\Demodata\DemoDataModifierProvider.sql"
sqlcmd -S . -d "%DB_NAME%" -E -i "tmp\CQ2\Database\Demodata\DemoDataFact.sql"

sqlcmd -S . -d %DB_NAME% -E -Q "EXEC [CRC].[uspUpdateStep2LoadDataTables]"
sqlcmd -S . -d %DB_NAME% -E -Q "EXEC CRC.uspUpdateStep3IndexDataTables"
sqlcmd -S . -d %DB_NAME% -E -Q "EXEC CRC.uspUpdateStep4CreateCQ2Tables"
sqlcmd -S . -d %DB_NAME% -E -Q "EXEC CRC.uspUpdateStep5SwapTables"
sqlcmd -S . -d %DB_NAME% -E -Q "EXEC CRC.uspUpdateStep6DropOldTables"

sqlcmd -S . -d %DB_NAME% -E -Q "INSERT INTO CRC.PATIENT_MAPPING SELECT CAST(PATIENT_NUM AS VARCHAR(50)), 'HIVE', PATIENT_NUM, 'A', 'demo', NULL, NULL, NULL, NULL, NULL, NULL FROM CRC.PATIENT_DIMENSION"
sqlcmd -S . -d %DB_NAME% -E -Q "INSERT INTO CRC.ENCOUNTER_MAPPING SELECT CAST(ENCOUNTER_NUM AS VARCHAR(50)), 'HIVE', 'demo', ENCOUNTER_NUM, CAST(PATIENT_NUM AS VARCHAR(50)), 'HIVE', 'A', NULL, NULL, NULL, NULL, NULL, NULL FROM CRC.VISIT_DIMENSION"

sqlcmd -S . -d "%DB_NAME%" -E -i "tmp\CQ2\Database\CreateAccount.sql"

sqlcmd -S . -d %DB_NAME% -E -Q "update PM.PM_CELL_DATA set URL = Case when Cell_ID = 'CRC' then 'http://localhost/CQ2/?/QueryToolService/' when CELL_ID = 'ONT' then 'http://localhost/CQ2/?/OntologyService/' when CELL_ID = 'WORK' THEN 'http://localhost/CQ2/?/WorkplaceService/' else '' END"

REM sqlcmd -S . -d %DB_NAME% -E -Q "update PM.PM_CELL_DATA set URL = Case when Cell_ID = 'CRC' then 'http://localhost/i2b2ServerProxy/CQ2ServiceProxy.php/QueryToolService/' when CELL_ID = 'ONT' then 'http://localhost/i2b2ServerProxy/CQ2ServiceProxy.php/OntologyService/' when CELL_ID = 'WORK' THEN 'http://localhost/i2b2ServerProxy/CQ2ServiceProxy.php/WorkplaceService/' else '' END"

